server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kirill
    username: postgres
    password: 9wti25c96i
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation:true

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info


#lob:
#
#logging:
#level:
#root:info
#org.springframework.web:info
#org.springframework.security:info
#org.springframework.security.oauth2:info
#
